packages:
  - apps/*
  - packages/*
catalog:
  "@tanstack/react-query": ^5.66.0
  "@tanstack/react-query-devtools": ^5.66.0
  "@tanstack/react-router": ^1.121.27
  "@tanstack/react-router-devtools": ^1.121.27
  "@tanstack/react-router-with-query": ^1.121.27
  "@tanstack/react-start": ^1.121.32
  "@types/node": ^22.5.4
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  autoprefixer: ^10.4.20
  postcss: ^8.5.1
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  redaxios: ^0.5.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  turbo: ^2.5.4
  typescript: ^5.8.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
