packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.29.0
  "@next/eslint-plugin-next": ^15.3.0
  "@tailwindcss/cli": ^4.1.5
  "@tailwindcss/postcss": ^4.1.10
  "@tailwindcss/vite": ^4.1.10
  "@tanstack/react-query": ^5.66.0
  "@tanstack/react-query-devtools": ^5.66.0
  "@tanstack/react-router": ^1.121.27
  "@tanstack/react-router-devtools": ^1.121.27
  "@tanstack/react-router-with-query": ^1.121.27
  "@tanstack/react-start": ^1.121.32
  "@trivago/prettier-plugin-sort-imports": ^5.2.2
  "@types/node": ^24.0.3
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  autoprefixer: ^10.4.20
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.2.0
  postcss: ^8.5.1
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  react-dom: ^19.0.0
  redaxios: ^0.5.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  turbo: ^2.5.4
  typescript: ^5.8.2
  typescript-eslint: ^8.34.0
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
